services:
  app:
    image: ${EMBYPROXY_IMAGE:-ghcr.io/hkfires/embyproxy:latest}
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: embyproxy
    restart: unless-stopped
    ports:
      - "${PORT:-8787}:${PORT:-8787}"
    volumes:
      - ./data:/app/data
    environment:
      PORT: "${PORT:-8787}"
    env_file:
      - .env
